import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import type { AddressInfo } from 'node:net';
import { WebSocket } from 'ws';
import { loadConfig } from '../src/server/config.js';
import { startServer } from '../src/server/server.js';
import type { ServerMsg, ClientMsg } from '../src/shared/protocol.js';

test('HTTP/WebSocket offices isolate tasks, chat and worker commands; archive is reversible', { timeout: 20000 }, async (t) => {
  const root = mkdtempSync(path.join(tmpdir(), 'office-isolation-'));
  const bin = path.join(root, 'bin'); mkdirSync(bin);
  // No provider or GitHub access: these fixtures cannot make external calls.
  for (const name of ['claude', 'gh']) writeFileSync(path.join(bin, name), '#!/bin/sh\nexit 1\n', { mode: 0o700 });
  const originalPath = process.env.PATH;
  process.env.PATH = `${bin}:${originalPath}`;
  t.after(() => { process.env.PATH = originalPath; rmSync(root, { recursive: true, force: true }); });
  const cfg = loadConfig(['--home', path.join(root, 'home'), '--password', 'fixture-password', '--host', '127.0.0.1', '--agent', '/bin/cat']);
  cfg.port = 0; cfg.city = undefined; cfg.webhook = undefined;
  const app = await startServer(cfg);
  t.after(() => app.shutdown());
  const port = (app.server.address() as AddressInfo).port;
  const origin = `http://127.0.0.1:${port}`;
  const login = await fetch(`${origin}/api/login`, { method: 'POST', headers: { 'content-type': 'application/json', origin }, body: JSON.stringify({ password: 'fixture-password' }) });
  assert.equal(login.status, 200);
  const cookie = login.headers.get('set-cookie')!.split(';')[0];
  async function connect() {
    const messages: ServerMsg[] = [];
    const socket = new WebSocket(`ws://127.0.0.1:${port}/ws?name=Tester`, { headers: { cookie, origin } });
    socket.on('message', (raw) => messages.push(JSON.parse(raw.toString())));
    t.after(() => socket.terminate());
    const next = async (predicate: (msg: ServerMsg) => boolean) => {
      const until = Date.now() + 4000;
      while (Date.now() < until) {
        const index = messages.findIndex(predicate);
        if (index >= 0) return messages.splice(index, 1)[0];
        await new Promise((r) => setTimeout(r, 10));
      }
      throw new Error('No matching server message: ' + JSON.stringify(messages.map((x) => x.t)));
    };
    await next((m) => m.t === 'welcome');
    return { socket, next, messages, send: (msg: ClientMsg) => socket.send(JSON.stringify(msg)) };
  }
  const a = await connect();
  a.send({ t: 'office.create', name: 'A' });
  const enteredA = await a.next((m) => m.t === 'floor.enter');
  assert.equal(enteredA.t, 'floor.enter'); if (enteredA.t !== 'floor.enter') return;
  const officeA = enteredA.floor!;
  a.send({ t: 'queue.limit', officeId: officeA, maxWorkers: 0 });
  await a.next((m) => m.t === 'queue' && m.state.maxWorkers === 0);
  a.send({ t: 'queue.add', officeId: officeA, prompt: 'Only A' });
  const added = await a.next((m) => m.t === 'queue' && m.state.tasks.length === 1);
  assert.equal(added.t, 'queue'); if (added.t !== 'queue') return;
  const task = added.state.tasks[0];
  a.send({ t: 'chat', officeId: officeA, text: 'Private to office A' });
  await a.next((m) => m.t === 'chat');
  a.send({ t: 'worker.spawn', officeId: officeA, kind: 'shell', deskId: 'desk-1' });
  const spawned = await a.next((m) => m.t === 'worker.update');
  assert.equal(spawned.t, 'worker.update'); if (spawned.t !== 'worker.update') return;
  const workerId = spawned.worker.id;
  const b = await connect();
  b.send({ t: 'office.create', name: 'B' });
  const enteredB = await b.next((m) => m.t === 'floor.enter');
  assert.equal(enteredB.t, 'floor.enter'); if (enteredB.t !== 'floor.enter') return;
  const officeB = enteredB.floor!;
  assert.deepEqual(enteredB.queue.tasks, []); assert.deepEqual(enteredB.workers, []); assert.deepEqual(enteredB.chat, []);
  b.send({ t: 'worker.kill', officeId: officeB, workerId });
  const denied = await b.next((m) => m.t === 'toast' && /No such worker/.test(m.text)); assert.equal(denied.t, 'toast');
  assert.ok(app.floors().find((f) => f.id === officeA)!.workers.get(workerId));
  b.send({ t: 'task.update', officeId: officeB, taskId: task.id, version: task.version!, update: { status: 'blocked', note: 'Wrong office' } });
  await b.next((m) => m.t === 'toast' && /No such task/.test(m.text));
  b.send({ t: 'queue.add', officeId: officeA, prompt: 'Stale context' });
  await b.next((m) => m.t === 'toast' && /context changed/.test(m.text));
  b.send({ t: 'queue.add', prompt: 'Old client' });
  await b.next((m) => m.t === 'toast' && /outdated/.test(m.text));
  assert.equal(app.floors().find((f) => f.id === officeB)!.queue.state().tasks.length, 0);
  a.send({ t: 'chat', officeId: officeA, text: 'Still only A' });
  await a.next((m) => m.t === 'chat' && m.text === 'Still only A');
  b.send({ t: 'ping', at: 123 }); await b.next((m) => m.t === 'pong' && m.at === 123);
  assert.ok(!b.messages.some((m) => m.t === 'chat' && m.text === 'Still only A'));
  b.send({ t: 'office.rename', officeId: officeB, name: 'B renamed' });
  await b.next((m) => m.t === 'floor.enter' && m.project?.name === 'B renamed');
  b.send({ t: 'office.archive', officeId: officeA, archived: true });
  await b.next((m) => m.t === 'toast' && /before archiving/.test(m.text));
  b.send({ t: 'office.archive', officeId: officeB, archived: true });
  await b.next((m) => m.t === 'floor.enter' && m.floor !== officeB);
  assert.ok(!app.floors().some((f) => f.id === officeB));
  b.send({ t: 'office.archive', officeId: officeB, archived: false });
  await b.next((m) => m.t === 'floors' && m.floors.some((f) => f.id === officeB && !f.archivedAt));
  b.send({ t: 'floor.go', floor: officeA });
  const switched = await b.next((m) => m.t === 'floor.enter' && m.floor === officeA);
  assert.equal(switched.t, 'floor.enter'); if (switched.t === 'floor.enter') assert.equal(switched.chat?.length, 2);
});
